In [1]:
import numpy as np
import scipy as sp
print(np.__version__)

1.20.3


### Numpy array
#### one-dimensional array

In [2]:
L = list(range(20))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [3]:
first_array = np.array(L)

In [5]:
print(first_array)
print(type(first_array)) #first_array data type

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>


In [6]:
first_array_than_10 = np.where(first_array>10)
first_array_than_10

(array([11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64),)

In [8]:
# other than
print(first_array[np.where(first_array>10)])

[11 12 13 14 15 16 17 18 19]


In [9]:
first_array.shape 

(20,)

In [11]:
# finding the mean, std and the range of first_array
first_array_mean = first_array.mean()
first_array_std = first_array.std()
first_array_max = first_array.max()
first_array_min = first_array.min()

# range = highest - lowest
first_array_range = first_array_max - first_array_min
print('first_array_mean: ',first_array_mean)
print('first_array_std: ', first_array_std)
print('first_array_std: ', first_array_range)

first_array_mean:  9.5
first_array_std:  5.766281297335398
first_array_std:  19


#### Simple Mathematics calculations with first_array

In [13]:
first_array_add5 = first_array + 5
first_array_add5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [15]:
first_add_mult_half = first_array * 0.5
first_add_mult_half

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [16]:
first_add_div_half = first_array / 10
first_add_div_half

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [17]:
# division of the first_array
# in combinations of first_array with first_add_mult_half
first_array_combine_div = first_array / first_add_mult_half
first_array_combine_div

C:\Users\hp\AppData\Local\Temp/ipykernel_7752/4159520692.py:3: RuntimeWarning: invalid value encountered in true_divide
  first_array_combine_div = first_array / first_add_mult_half


array([nan,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.])

In [19]:
first_array_combine_div1 = first_array /  first_add_div_half
first_array_combine_div1

C:\Users\hp\AppData\Local\Temp/ipykernel_7752/3123316787.py:1: RuntimeWarning: invalid value encountered in true_divide
  first_array_combine_div1 = first_array /  first_add_div_half


array([nan, 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10.])

In [20]:
# Acessing Single Element
print(first_array[8])
print(first_array[5:15])
print(first_array[1:13:2])

8
[ 5  6  7  8  9 10 11 12 13 14]
[ 1  3  5  7  9 11]


##### concatenations of one-dimentional array

In [21]:
first_array_concatenate = np.concatenate([first_array_add5, 
                                          first_add_div_half])
first_array_concatenate

array([ 5. ,  6. ,  7. ,  8. ,  9. , 10. , 11. , 12. , 13. , 14. , 15. ,
       16. , 17. , 18. , 19. , 20. , 21. , 22. , 23. , 24. ,  0. ,  0.1,
        0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,  1.2,
        1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9])

In [32]:
print(np.concatenate([first_array[1:13:2], first_array[::-1]]))

[ 1  3  5  7  9 11 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [36]:
#other thanprint
(np.r_[first_array[1:13:2], first_array[::-1]])

array([ 1,  3,  5,  7,  9, 11, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,
        8,  7,  6,  5,  4,  3,  2,  1,  0])

### Two-Dimensional array

In [43]:
two_array_zero = np.zeros((2,2))
two_array

array([[0., 0.],
       [0., 0.]])

In [44]:
two_array_ones = np.ones((2,2))
two_array_ones

array([[1., 1.],
       [1., 1.]])

In [46]:
# random chosen number
two_array_empty = np.empty((2,2))
two_array_empty

array([[1., 1.],
       [1., 1.]])

In [48]:
oneD_array = np.arange(8)
oneD_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [60]:
twoD_array = oneD_array.reshape(2,4)
print(twoD_array)
print('twoD_array: ', twoD_array.shape)

[[0 1 2 3]
 [4 5 6 7]]
twoD_array:  (2, 4)


In [58]:
twoD_array_transpose = twoD_array.T
print(twoD_array_transpose)
print('twoD_array_transpose:',twoD_array_transpose.shape)


[[0 4]
 [1 5]
 [2 6]
 [3 7]]
twoD_array_transpose: (4, 2)


In [56]:
print(np.linspace(1,6,4))

[1.         2.66666667 4.33333333 6.        ]


In [63]:
X = np.arange(10).reshape(5,2)
twoX = X + X

In [78]:
# addition of new column
X_add_col =X[:, np.newaxis]
print(X_add_col)
print(X_add_col.shape) #implies 1 X 2 five times

[[[0 1]]

 [[2 3]]

 [[4 5]]

 [[6 7]]

 [[8 9]]]
(5, 1, 2)


In [76]:
#X_add_col and twoX 
X_add =twoX +X_add_col
print(X_add)
print(X_add.shape)

[[[ 0  3]
  [ 4  7]
  [ 8 11]
  [12 15]
  [16 19]]

 [[ 2  5]
  [ 6  9]
  [10 13]
  [14 17]
  [18 21]]

 [[ 4  7]
  [ 8 11]
  [12 15]
  [16 19]
  [20 23]]

 [[ 6  9]
  [10 13]
  [14 17]
  [18 21]
  [22 25]]

 [[ 8 11]
  [12 15]
  [16 19]
  [20 23]
  [24 27]]]
(5, 5, 2)


#### matrix slicing

In [82]:
# getting X_add all first column
## fc = first of first column
X_add_fc = X_add[0][0]
X_add_fc

array([0, 3])

In [84]:
# giving another number to last matrix first row and frist column
X_add[4,0] = [5,-1]
X_add

array([[[ 0,  3],
        [ 4,  7],
        [ 8, 11],
        [12, 15],
        [16, 19]],

       [[ 2,  5],
        [ 6,  9],
        [10, 13],
        [14, 17],
        [18, 21]],

       [[ 4,  7],
        [ 8, 11],
        [12, 15],
        [16, 19],
        [20, 23]],

       [[ 6,  9],
        [10, 13],
        [14, 17],
        [18, 21],
        [22, 25]],

       [[ 5, -1],
        [12, 15],
        [16, 19],
        [20, 23],
        [24, 27]]])

In [90]:
# checking the last matrix 3rd row and first element  
print(X_add[4,2,0] == [3,1])

[False False]


In [91]:
# checking the last matrix 3rd row and first element 
print(X_add[4,2,0] == [16])

[ True]


### checking random numbers

In [92]:
# letting the random not to fade away incase of any other useage
np.random.seed(1)
x = np.random.randn(100)
x

array([ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
       -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038,
        1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944,
       -1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521,
       -1.10061918,  1.14472371,  0.90159072,  0.50249434,  0.90085595,
       -0.68372786, -0.12289023, -0.93576943, -0.26788808,  0.53035547,
       -0.69166075, -0.39675353, -0.6871727 , -0.84520564, -0.67124613,
       -0.0126646 , -1.11731035,  0.2344157 ,  1.65980218,  0.74204416,
       -0.19183555, -0.88762896, -0.74715829,  1.6924546 ,  0.05080775,
       -0.63699565,  0.19091548,  2.10025514,  0.12015895,  0.61720311,
        0.30017032, -0.35224985, -1.1425182 , -0.34934272, -0.20889423,
        0.58662319,  0.83898341,  0.93110208,  0.28558733,  0.88514116,
       -0.75439794,  1.25286816,  0.51292982, -0.29809284,  0.48851815,
       -0.07557171,  1.13162939,  1.51981682,  2.18557541, -1.39

In [94]:
binss = np.linspace(-5, 5, 20)
counted = np.zeros_like(binss)
print(binss)
print(counted)

[-5.         -4.47368421 -3.94736842 -3.42105263 -2.89473684 -2.36842105
 -1.84210526 -1.31578947 -0.78947368 -0.26315789  0.26315789  0.78947368
  1.31578947  1.84210526  2.36842105  2.89473684  3.42105263  3.94736842
  4.47368421  5.        ]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [107]:
np.random.seed(1)
y = np.random.RandomState(1)
y_int = y.randint(0, 20, (4,6)) # 0 to 20, 4 row and 6 column
print(y)
print(y_int)


RandomState(MT19937)
[[ 5 11 12  8  9 11]
 [ 5 15  0 16  1 12]
 [ 7 13  6 18  5 18]
 [11 10 14 18  4  9]]


In [108]:
y_int_sort = np.sort(y_int, axis=1) #axis=1 sort the rows
y_int_sort

array([[ 5,  8,  9, 11, 11, 12],
       [ 0,  1,  5, 12, 15, 16],
       [ 5,  6,  7, 13, 18, 18],
       [ 4,  9, 10, 11, 14, 18]])

In [112]:
y_hstack = np.hstack((y_int_sort, y_int))
y_hstack

array([[ 5,  8,  9, 11, 11, 12,  5, 11, 12,  8,  9, 11],
       [ 0,  1,  5, 12, 15, 16,  5, 15,  0, 16,  1, 12],
       [ 5,  6,  7, 13, 18, 18,  7, 13,  6, 18,  5, 18],
       [ 4,  9, 10, 11, 14, 18, 11, 10, 14, 18,  4,  9]])

In [113]:
y_vstack = np.vstack((y_int_sort, y_int))
y_vstack

array([[ 5,  8,  9, 11, 11, 12],
       [ 0,  1,  5, 12, 15, 16],
       [ 5,  6,  7, 13, 18, 18],
       [ 4,  9, 10, 11, 14, 18],
       [ 5, 11, 12,  8,  9, 11],
       [ 5, 15,  0, 16,  1, 12],
       [ 7, 13,  6, 18,  5, 18],
       [11, 10, 14, 18,  4,  9]])

### Using scipy to solve eigenvalues and eigenvectors

In [114]:
from scipy import linalg
test_data = np.array([[11, 0, 1],[3, -1, 4], [6, 7, -2]])
test_data

array([[11,  0,  1],
       [ 3, -1,  4],
       [ 6,  7, -2]])

In [122]:
test_data.trace()

8

In [115]:
eigenvalues, eigenvector = linalg.eig(test_data)

In [116]:
first_eigen, second_eigen, third_eigen = eigenvalues

In [118]:
print(first_eigen)
print(second_eigen)
print(third_eigen)

(11.668321041285413+0j)
(3.221627966157723+0j)
(-6.889949007443135+0j)


In [119]:
print(eigenvector[:,0])
print(eigenvector[:,1])
print(eigenvector[:,2])

[0.77915871 0.34893249 0.52072816]
[ 0.0971971  -0.64727389 -0.75603521]
[-0.04680143 -0.54477496  0.83727526]


In [121]:
from scipy.stats import norm
#random variables of 10 numbers
print('random_variable: ',norm.rvs(loc=1,scale=1,size=10))

# cumulative distribution function 5 number
print('cummulative_fuction: ',norm.cdf(5,loc=1,scale=2))

# probability density function 0f 10 number 
print('probability_density: ',norm.pdf(10,loc=0,scale=5))

random_variable:  [ 2.46210794 -1.06014071  0.6775828   0.61594565  2.13376944 -0.09989127
  0.82757179  0.12214158  1.04221375  1.58281521]
cummulative_fuction:  0.9772498680518208
probability_density:  0.010798193302637612


#### Calculating GDP with numpy

In [126]:
# certain gdp of some countries
countries =np.array(['Algeria','Angola','Argentina','Australia','Austria','Bahamas','Bangladesh',
                     'Belarus','Belgium','Bhutan','Brazil','Bulgaria','Cambodia','Cameroon',
                     'Chile','China','Colombia','Cyprus','Denmark','El Salvador','Estonia',
                     'Ethiopia','Fiji','Finland','France','Georgia','Ghana','Grenada',
                     'Guinea','Haiti','Honduras','Hungary','India','Indonesia','Ireland',
                     'Italy','Japan','Kenya', 'South Korea','Liberia','Malaysia','Mexico',
                     'Morocco','Nepal','New Zealand','Norway','Pakistan', 'Peru','Qatar',
                     'Russia','Singapore','South Africa','Spain','Sweden','Switzerland','Thailand',
                     'United Arab Emirates','United Kingdom','United States','Uruguay','Venezuela','Vietnam','Zimbabwe'])


countries_gdp = np.array([2255.225482,629.9553062,11601.63022,25306.82494,27266.40335,19466.99052,588.3691778,
                          2890.345675,24733.62696,1445.760002,4803.398244,2618.876037,590.4521124,665.7982328,
                          7122.938458,2639.54156,3362.4656,15378.16704,30860.12808,2579.115607,6525.541272,
                          229.6769525,2242.689259,27570.4852,23016.84778,1334.646773,402.6953275,6047.200797,
                          394.1156638,385.5793827,1414.072488,5745.981529,837.7464011,1206.991065,27715.52837,
                          18937.24998,39578.07441,478.2194906,16684.21278,279.2204061,5345.213415,6288.25324,
                          1908.304416,274.8728621,14646.42094,40034.85063,672.1547506,3359.517402,36152.66676,
                          3054.727742,33529.83052,3825.093781,15428.32098,33630.24604,39170.41371,2699.123242,
                          21058.43643,28272.40661,37691.02733,9581.05659,5671.912202,757.4009286,347.7456605])

max_countries_gdp = countries_gdp.argmax()

In [127]:
countries_with_highest_gdp = countries[max_countries_gdp]

In [128]:
countries_with_highest_gdp

'Norway'

In [129]:
min_countries_gdp = countries_gdp.argmin()
countries_with_lowest_gdp = countries[min_countries_gdp]
countries_with_lowest_gdp

'Ethiopia'

In [130]:
for counts in range(len(countries)):
    country =countries[counts]
    country_gdp = countries_gdp[counts]
    print("country {} GDP is {}".format(country,country_gdp))
       

country Algeria GDP is 2255.225482
country Angola GDP is 629.9553062
country Argentina GDP is 11601.63022
country Australia GDP is 25306.82494
country Austria GDP is 27266.40335
country Bahamas GDP is 19466.99052
country Bangladesh GDP is 588.3691778
country Belarus GDP is 2890.345675
country Belgium GDP is 24733.62696
country Bhutan GDP is 1445.760002
country Brazil GDP is 4803.398244
country Bulgaria GDP is 2618.876037
country Cambodia GDP is 590.4521124
country Cameroon GDP is 665.7982328
country Chile GDP is 7122.938458
country China GDP is 2639.54156
country Colombia GDP is 3362.4656
country Cyprus GDP is 15378.16704
country Denmark GDP is 30860.12808
country El Salvador GDP is 2579.115607
country Estonia GDP is 6525.541272
country Ethiopia GDP is 229.6769525
country Fiji GDP is 2242.689259
country Finland GDP is 27570.4852
country France GDP is 23016.84778
country Georgia GDP is 1334.646773
country Ghana GDP is 402.6953275
country Grenada GDP is 6047.200797
country Guinea GDP is 

In [131]:
highest_country_gdp = max(countries_gdp)
highest_country_gdp

40034.85063

In [132]:
lowest_country_gdp = min(countries_gdp)
lowest_country_gdp

229.6769525

In [133]:
# the mean and standard deviation of the countries_gdp
mean_countries_gdp = np.mean(countries_gdp)
print(mean_countries_gdp)
std_countries_gdp = np.std(countries_gdp)
print(std_countries_gdp)

11289.409271639683
12743.828910617945


##### Gross domestic product 2021

In [149]:
world_zone = np.array(['East Asia & Pacific','Europe & Central Asia','Latin America & Caribbean',
                        'Middle East & North Africa','North America','South Asia','Sub-Saharan Africa'])
world_zone_gdp = np.array([30880832,25046913,5488720,3636732,24993943,4087774,1917904,])

In [151]:
max_world_zone_gdp = world_zone_gdp.argmax()
max_world_zone_gdp = world_zone[max_world_zone_gdp]
max_world_zone_gdp

'East Asia & Pacific'

In [152]:
min_world_zone_gdp = world_zone_gdp.argmin()
min_world_zone_gdp = world_zone[min_world_zone_gdp]
min_world_zone_gdp

'Sub-Saharan Africa'